### ISSUE TITLE
API Despesas: Exibir despesa por ID

### ISSUE THREAD

**Issue by Gabriel-P22** [meajuda-dev/Despesas-Back-Java#7]
**Escopo:**
Criar endpoint de API para exibir os dados de uma despesa a partir do ID

**Definição da API:**
URL: `http://localhost:3001/api/v1/expenses/1`
REQUEST METHOD: `GET`
REQUEST PAYLOAD: N/A
RESPONSE STATUS CODE: `200 OK`
RESPONSE BODY:
```
{
    "id": 1,
    "description": "Internet",
    "value": 99.90,
    "is_fixed": true,
    "due_date": "2021-04-08",
    "category_id": [1,5,3],
    "user_id": 1,
}
```

**Definição de Pronto**:
API funcional, retornando dados vindos do banco de dados

**Comment by francisrod01** [comment]
Merged & completed! :rocket: :tada:
